### ISSUE TITLE
Work with Chris Maltby on replacing outdated GBT Player in GB Studio with DevSound

### ISSUE THREAD

**Issue by darkhog** [DevEd2/DevSound#17]
Please work with Chris Maltby on replacing GBT Player, which isn't very good and doesn't do a lot of things a sound engine should with DevSound. GB Studio repo: https://github.com/chrismaltby/gb-studio

**Comment by ISSOtm** [comment]
That would happen only if GB Studio moved from GBDK to RGBDS, for starters.

**Comment by DevEd2** [comment]
DevSound also doesn't have any dedicated editor at the moment; the only real option is to manually program the music data in, which would defeat the entire point of GB Studio (i.e. the ability to make games without any programming skill). Making an editor for DevSound myself is not an option at the moment since I don't have the time for it. Closing this for now.

**Comment by Pigu-A** [comment]
https://github.com/chrismaltby/gb-studio/issues/44#issuecomment-487903101

What DevEd said, I could add the support for it now but the lack of editor for it will still render it useless. I would write an editor for it too if I have the a and proper web dev knowledge.
